### ISSUE TITLE
Quasar version

### ISSUE THREAD

**Issue by nothingismagick** [wmfs/cardscript#97]
So I saw that you are following the good practice of locking your dependencies to specific versions, however I have to recommend that you update to latest stable quasar, especially because there is going to be a bit of cognitive load when you move to 1.0 next year...

https://github.com/wmfs/cardscript/blob/5f58671d89fed53e6f137011b884d9acf61c6bc1/packages/cardscript-quasar-playpen/package.json#L45

That said, there is going to be a lot of one-time interface changes to catch up with the new quasar API, look forward to helping you all transition.

**Comment by timneedham** [comment]
Closed by 9b943134e335a303384ee150500aae01cdd1bbe5

**Comment by nothingismagick** [comment]
0.17.23 just released - important autocomplete issue resolved!!!
