### ISSUE TITLE
Dead links in CardScript Playpen

### ISSUE THREAD

**Issue by MichaelJCole** [wmfs/cardscript#99]
Hi, on the CardScript Playpen I found some dead links:  https://wmfs.github.io/cardscript/

Examples -> Expressions -> Template Tab:

```
https://github.com/wmfs/cardscript/tree/master/packages/cardscript-to-quasar
https://github.com/wmfs/cardscript/tree/master/packages/cardscript-extract-lists
```

**Comment by meenahoda** [comment]
Hey,

Good spot! Thank you for raising this issue 😄
Cardscript was previously a monorepo but since we extracted the packages we forgot to update these links. I've corrected them now and shall do a build.

Cheers,
Meena
